# Generated by Django 6.0.7 on 2026-09-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reason',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='species_breed',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
