# Generated by Django 6.0.7 on 2026-09-06 04:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_enquiry_last_name_alter_enquiry_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='girth_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Limb circumference — the usual proxy for muscle mass.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='lameness_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 — Sound'), (1, '1 — Mild, intermittent'), (2, '2 — Mild, consistent'), (3, '3 — Moderate, obvious at walk'), (4, '4 — Non-weight-bearing')], help_text='Covers gait and weight-bearing in one validated grade.', null=True),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='pain_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 = no pain, 10 = worst possible.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='rom_degrees',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Range of motion at `rom_joint`, in degrees.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='rom_joint',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
