# Generated by Django 6.0.7 on 2026-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_progressnote_girth_cm_progressnote_lameness_score_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Cancelled'), _negated=True), fields=('pet', 'date', 'time'), name='uniq_active_appointment_per_pet_slot'),
        ),
    ]
