# Generated by Django 6.0.7 on 2026-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_money_guards_and_email_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('Initial', 'Initial Consultation'), ('Followup', 'Follow-up Session'), ('Reassessment', 'Re-assessment'), ('Hydrotherapy', 'Hydrotherapy'), ('LaserTherapy', 'Laser Therapy')], default='Initial', max_length=50),
        ),
    ]
