# Generated by Django 6.0.7 on 2026-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='service',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
