# Generated by Django 6.0.7 on 2026-09-21 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_enquiry_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=12)),
                ('date', models.DateField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('pet_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date', 'slot', 'created_at'),
                'indexes': [models.Index(fields=['date', 'slot', 'status'], name='appointment_date_280398_idx')],
            },
        ),
    ]
