# Generated by Django 6.0.7 on 2026-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_facilitybooking_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitybooking',
            name='bed_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='facilitybooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('HELD', 'PENDING', 'CONFIRMED'))), fields=('date', 'slot', 'bed_index'), name='uniq_active_bed_per_date_slot'),
        ),
    ]
