# Generated by Django 6.0.7 on 2026-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_facilitybooking_bed_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('Initial', 'Initial Consultation'), ('Followup', 'Follow-up Session'), ('Reassessment', 'Re-assessment'), ('Hydrotherapy', 'Hydrotherapy'), ('LaserTherapy', 'Laser Therapy'), ('Physiotherapy', 'Physiotherapy'), ('IndoorFacility', 'Indoor Facility (Day Care)'), ('Grooming', 'Grooming'), ('Walking', 'Walking')], default='Initial', max_length=50),
        ),
    ]
