# Generated by Django 6.0.8 on 2026-09-30 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0014_alter_appointment_visit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardingBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(db_index=True, max_length=16)),
                ("pet_name", models.CharField(max_length=100)),
                ("owner_name", models.CharField(max_length=150)),
                ("owner_phone", models.CharField(max_length=50)),
                (
                    "owner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("check_in", models.DateField()),
                ("duration", models.CharField(max_length=12)),
                ("check_out", models.DateField()),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "food_by",
                    models.CharField(
                        choices=[("clinic", "Clinic"), ("owner", "Owner")],
                        default="owner",
                        max_length=6,
                    ),
                ),
                (
                    "utensils_by",
                    models.CharField(
                        choices=[("clinic", "Clinic"), ("owner", "Owner")],
                        default="owner",
                        max_length=6,
                    ),
                ),
                (
                    "medicines_by",
                    models.CharField(
                        choices=[("clinic", "Clinic"), ("owner", "Owner")],
                        default="owner",
                        max_length=6,
                    ),
                ),
                (
                    "blanket_by",
                    models.CharField(
                        choices=[("clinic", "Clinic"), ("owner", "Owner")],
                        default="owner",
                        max_length=6,
                    ),
                ),
                (
                    "food_preference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("walk_times", models.JSONField(blank=True, default=list)),
                ("aadhaar", models.CharField(blank=True, default="", max_length=12)),
                ("terms_accepted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked in"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="owner", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["check_in", "check_out", "status"],
                        name="appointment_check_i_936d41_idx",
                    )
                ],
            },
        ),
    ]
