# Generated by Django 5.1.14 on 2026-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0015_boardingbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingbooking",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
