# Generated by Django 6.0.9 on 2026-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_boardingbooking_checked_in_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='report_type',
            field=models.CharField(choices=[('XRAY', 'X-Ray'), ('MRI', 'MRI'), ('CT', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('BLOOD', 'Blood Report'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
