# Generated by Django 6.0.9 on 2026-10-08 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_blood_report_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RehabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('therapy', models.CharField(max_length=100)),
                ('planned_date', models.DateField()),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='DUE', max_length=10)),
                ('done_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('skip_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='appointments.treatmentplan')),
            ],
            options={
                'ordering': ['planned_date', 'therapy'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'therapy', 'planned_date'), name='uniq_rehab_session_cell')],
            },
        ),
    ]
