# Generated by Django 6.0.9 on 2026-10-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_boarding_emergency_links_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingbooking',
            name='requester_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
