# Generated by Django 6.0.9 on 2026-10-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_converted_enquiries(apps, schema_editor):
    """A converted enquiry was linked to an owner by the clinic's own action --
    carry that link onto the new `owner` column so the owner keeps seeing it once
    phone matching is removed from /owner/bookings. Nothing else is backfilled:
    an automatic phone match is not proof of identity (live QA D1)."""
    Enquiry = apps.get_model("appointments", "Enquiry")
    for enquiry in Enquiry.objects.filter(
        status="CONVERTED", owner__isnull=True, converted_appointment__isnull=False,
    ).select_related("converted_appointment__pet"):
        pet = enquiry.converted_appointment.pet
        if pet is not None and pet.owner_id:
            enquiry.owner_id = pet.owner_id
            enquiry.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_boarding_hold_requester_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boardingbooking',
            name='owner_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(link_converted_enquiries, migrations.RunPython.noop),
    ]
