# Generated by Django 6.0.9 on 2026-10-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_converted_enquiries(apps, schema_editor):
    """Carry the clinic's own link onto the new `owner` column -- but only where
    convert CREATED that owner account (unusable password, joined no earlier
    than the enquiry). An enquiry converted onto an account that already
    existed was matched by unverified email and stays unlinked until staff
    explicitly confirm the client (live QA D1 review)."""
    Enquiry = apps.get_model("appointments", "Enquiry")
    for enquiry in Enquiry.objects.filter(
        status="CONVERTED", owner__isnull=True, converted_appointment__isnull=False,
    ).select_related("converted_appointment__pet__owner"):
        pet = enquiry.converted_appointment.pet
        owner = pet.owner if pet is not None else None
        if owner is None:
            continue
        created_by_convert = (
            (owner.password or "").startswith("!") and owner.date_joined >= enquiry.created_at
        )
        if created_by_convert:
            enquiry.owner_id = owner.id
            enquiry.owner_verified = True
            enquiry.save(update_fields=["owner", "owner_verified"])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_boarding_hold_requester_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boardingbooking',
            name='owner_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitybooking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='owner_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(link_converted_enquiries, migrations.RunPython.noop),
    ]
