# Generated by Django 6.0.9 on 2026-10-08 12:07

import appointments.models.files
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_boarding_hold_requester_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='file',
            field=models.FileField(upload_to=appointments.models.files.diagnostic_report_upload_to),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=appointments.models.files.pet_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='queryattachment',
            name='file',
            field=models.FileField(upload_to=appointments.models.files.query_attachment_upload_to),
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.BinaryField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
