# Generated by Django 6.0.9 on 2026-10-08 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_stored_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('appointment_confirmed', 'Appointment confirmed'), ('appointment_reminder', 'Appointment reminder'), ('boarding_confirmed', 'Boarding confirmed'), ('boarding_checkout', 'Boarding check-out reminder'), ('test', 'Test message')], max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED_OPTOUT', 'Skipped (owner opted out)'), ('SKIPPED_LIMIT', 'Skipped (daily limit reached)'), ('SKIPPED_DISABLED', 'Skipped (SMS disabled)')], default='QUEUED', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='appointments.appointment')),
                ('boarding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='appointments.boardingbooking')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
