# Generated by Django 6.0.9 on 2026-10-08 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='kind',
            field=models.CharField(choices=[('appointment_confirmed', 'Appointment confirmed'), ('appointment_moved', 'Appointment moved'), ('appointment_reminder', 'Appointment reminder'), ('boarding_confirmed', 'Boarding confirmed'), ('boarding_checkout', 'Boarding check-out reminder'), ('test', 'Test message')], max_length=40),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED_OPTOUT', 'Skipped (owner opted out)'), ('SKIPPED_LIMIT', 'Skipped (daily limit reached)'), ('SKIPPED_COUNTRY', 'Skipped (country not allowed)'), ('SKIPPED_DISABLED', 'Skipped (SMS disabled)')], default='QUEUED', max_length=20),
        ),
    ]
