# Generated by Django 6.0.9 on 2026-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_appointment_confirmed_sms_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='blob_url',
            field=models.CharField(blank=True, db_default='', default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
